<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002154017 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблиц products, product_attributes, product_images.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, value TEXT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_attributes_product_id ON product_attributes (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_attributes_product_key ON product_attributes (product_id, key)');
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(2048) NOT NULL, path VARCHAR(2048) DEFAULT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_images_product_id ON product_images (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_images_product_url ON product_images (product_id, url)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_code VARCHAR(255) NOT NULL, name VARCHAR(512) NOT NULL, description TEXT NOT NULL, price NUMERIC(15, 2) NOT NULL, purchase_price NUMERIC(15, 2) NOT NULL, discount NUMERIC(5, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5AE20A50B4 ON products (external_code)');
        $this->addSql('CREATE INDEX idx_products_name ON products (name)');
        $this->addSql('ALTER TABLE product_attributes ADD CONSTRAINT FK_A2FCC15B4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_attributes DROP CONSTRAINT FK_A2FCC15B4584665A');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('DROP TABLE product_attributes');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE products');
    }
}
